# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Orlando Code Camp
email: board@orlandocodecamp.com
description: >-
  Orlando Code Camp 2026 - April 11th 2026 @ Seminole State College, Sanford, FL.
  Central Florida's premier free technology conference.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://orlandocodecamp.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: onetug
github_username: onetug
search_enabled: false

# Build settings
markdown: kramdown

# Disable themes - using custom design
theme: null
remote_theme: null

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

kramdown:
  hard_wrap: true

sass:
  sass_dir: _sass
  style: compressed

# Default front matter values
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Navigation settings
nav_external_links_new_tab: true
